export interface Books {
    id: number;
    name: string;
    genre: string;
    type: string;
    pages: number;
    author: string;
    date: Date;
    price: number;
    amount: number;
    status?: string;
  }
  
  export class BookService {
    private books: Array<Books> = [
      {
        id: 1,
        name: '12 rules of life',
        genre: 'Psihology',
        type: 'Book',
        pages: 120,
        author: 'Jordan B. Peterson',
        date: new Date('2018-01-16 21:00'),
        amount: 1,
        price: 19.99,
        },
        {
        id: 2,
        name: 'To Kill a Mockingbird',
        genre: 'Classic',
        type: 'Book',
        pages: 281,
        author: 'Harper Lee',
        date: new Date('2022-07-15 10:30'),
        amount: 1,
        price: 12.99,
        },
        {
        id: 3,
        name: '1984',
        genre: 'Dystopian',
        type: 'Book',
        pages: 328,
        author: 'George Orwell',
        date: new Date('2022-12-01 18:15'),
        amount: 1,
        price: 9.99,
        },
        {
        id: 4,
        name: 'The Great Gatsby',
        genre: 'Classic',
        type: 'Book',
        pages: 180,
        author: 'F. Scott Fitzgerald',
        date: new Date('2022-09-10 14:45'),
        amount: 1,
        price: 8.99,
        },
        {
        id: 5,
        name: 'Pride and Prejudice',
        genre: 'Romance',
        type: 'Book',
        pages: 279,
        author: 'Jane Austen',
        date: new Date('2022-11-25 09:00'),
        amount: 1,
        price: 14.99,
        },
        {
        id: 6,
        name: 'The Lord of the Rings',
        genre: 'Fantasy',
        type: 'Book',
        pages: 1178,
        author: 'J.R.R. Tolkien',
        date: new Date('2022-06-05 16:20'),
        amount: 1,
        price: 29.99,
        },
        {
        id: 7,
        name: 'Harry Potter and the Philosophers Stone',
        genre: 'Fantasy',
        type: 'Book',
        pages: 223,
        author: 'J.K. Rowling',
        date: new Date('2022-10-20 12:00'),
        amount: 1,
        price: 11.99,
        },
        {
        id: 8,
        name: 'The Catcher in the Rye',
        genre: 'Coming-of-Age',
        type: 'Book',
        pages: 224,
        author: 'J.D. Salinger',
        date: new Date('2022-08-15 17:30'),
        amount: 1,
        price: 10.99,
        },
        {
        id: 9,
        name: 'The Hobbit',
        genre: 'Fantasy',
        type: 'Book',
        pages: 310,
        author: 'J.R.R. Tolkien',
        date: new Date('2022-07-01 09:45'),
        amount: 1,
        price: 13.99,
        },
        {
        id: 10,
        name: 'Moby Dick',
        genre: 'Adventure',
        type: 'Book',
        pages: 585,
        author: 'Herman Melville',
        date: new Date('2022-09-05 14:15'),
        amount: 1,
        price: 15.99,
        },
        {
          id: 11,
          name: 'All Star Comics No. 8',
          genre: 'Manga',
          type: 'Magazine',
          pages: 200,
          author: 'Roy Thomas',
          date: new Date('2023-01-01 11:00'),
          amount: 1,
          price: 64.99,
          },
          {
          id: 12,
          name: 'National Geographic',
          genre: 'Science',
          type: 'Magazine',
          pages: 100,
          author: 'Various Authors',
          date: new Date('2022-12-20 09:30'),
          amount: 1,
          price: 9.99,
          },
          {
          id: 13,
          name: 'Vogue',
          genre: 'Fashion',
          type: 'Magazine',
          pages: 150,
          author: 'Various Authors',
          date: new Date('2022-11-15 14:00'),
          amount: 1,
          price: 12.99,
          },
          {
          id: 14,
          name: 'Sports Illustrated',
          genre: 'Sports',
          type: 'Magazine',
          pages: 80,
          author: 'Various Authors',
          date: new Date('2022-10-05 17:45'),
          amount: 1,
          price: 7.99,
          },
          {
          id: 15,
          name: 'Time',
          genre: 'News',
          type: 'Magazine',
          pages: 120,
          author: 'Various Authors',
          date: new Date('2022-09-10 10:15'),
          amount: 1,
          price: 6.99,
          },
          {
          id: 16,
          name: 'Cosmopolitan',
          genre: 'Lifestyle',
          type: 'Magazine',
          pages: 90,
          author: 'Various Authors',
          date: new Date('2022-08-05 12:30'),
          amount: 1,
          price: 4.99,
          },
          {
          id: 17,
          name: 'Wired',
          genre: 'Technology',
          type: 'Magazine',
          pages: 110,
          author: 'Various Authors',
          date: new Date('2022-07-20 15:00'),
          amount: 1,
          price: 8.99,
          },
          {
          id: 18,
          name: 'Food & Wine',
          genre: 'Culinary',
          type: 'Magazine',
          pages: 70,
          author: 'Various Authors',
          date: new Date('2022-06-15 18:30'),
          amount: 1,
          price: 5.99,
          },
          {
          id: 19,
          name: 'Scientific American',
          genre: 'Science',
          type: 'Magazine',
          pages: 95,
          author: 'Various Authors',
          date: new Date('2022-05-01 11:45'),
          amount: 1,
          price: 9.99,
          },
          {
          id: 20,
          name: 'Smithsonian',
          genre: 'History',
          type: 'Magazine',
          pages: 130,
          author: 'Various Authors',
          date: new Date('2022-04-05 14:00'),
          amount: 1,
          price: 7.99,
          }
    ];
  
    getBooks() {
        return this.books;
    }
  }
  